name: library_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^2.4.0
  country_picker: ^2.0.8
  cupertino_icons: ^1.0.2
  file_picker: ^4.0.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.3+3
  page_transition: ^2.0.4
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/books.jpeg
    - assets/images/wallpaper.jpg
    - assets/images/trojanHorse_Fictional.jpg
    - assets/images/biography.jpg
    - assets/images/comic.jpg
    - assets/images/design.jpg
    - assets/images/napoleon_historical.jpg
    - assets/images/plato_philosopher.jpg
    - assets/images/sci_fi.jpg
    - assets/images/bookBack.jpg
    - assets/images/dev.png
    - assets/images/partnership.png
    - assets/images/leaderShip.png
    - assets/images/team.png
    - assets/images/vision.png
    - assets/images/service.png
    - assets/images/CEO.png
    - assets/images/Co-Founder.png
    - assets/images/manager.png
    - assets/images/developer.png
    - assets/images/developer2.png
    - assets/images/germany.png
    - assets/images/greece.png
    - assets/images/norway.png
    - assets/images/denmark.png
    - assets/images/canada.png
    - assets/images/sending.png
    - assets/images/wink.png
    - assets/images/confirm.png
    - assets/images/location.png
    - assets/images/age.png
    - assets/images/booksIcon.png
    - assets/images/heart.png
    - assets/images/email-2.png
    - assets/images/password.png
    - assets/images/login.png
    - assets/images/error.png
    - assets/images/eye.png
    - assets/images/allBooks.png
    - assets/images/success.png
    - assets/images/categories.png
    - assets/images/fictional.jpg
    - assets/images/anneFrank.jpg
    - assets/images/wingedHussars.jpg
    - assets/images/comics.jpg
    - assets/images/sittingBull.jpg
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
